// <auto-generated />
using System;
using CNBot.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CNBot.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200414102916_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CNBot.Core.Entities.Chats.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("ChatType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8")
                        .HasMaxLength(4000);

                    b.Property<int>("MembersCount")
                        .HasColumnType("int");

                    b.Property<int>("TGChatId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(256) CHARACTER SET utf8")
                        .HasMaxLength(256);

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(128) CHARACTER SET utf8")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("TGChatId")
                        .IsUnique();

                    b.ToTable("chat");
                });

            modelBuilder.Entity("CNBot.Core.Entities.Chats.ChatMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TGUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("chat_member");
                });

            modelBuilder.Entity("CNBot.Core.Entities.Messages.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FromTGUserId")
                        .HasColumnType("int");

                    b.Property<int>("TGChatId")
                        .HasColumnType("int");

                    b.Property<int>("TGMessageId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8")
                        .HasMaxLength(4096);

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("message");
                });

            modelBuilder.Entity("CNBot.Core.Entities.Messages.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .HasColumnType("longtext CHARACTER SET utf8")
                        .HasMaxLength(4096);

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("Offset")
                        .HasColumnType("int");

                    b.Property<int?>("TGUserId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("varchar(1024) CHARACTER SET utf8")
                        .HasMaxLength(1024);

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("message_entity");
                });

            modelBuilder.Entity("CNBot.Core.Entities.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8")
                        .HasMaxLength(256);

                    b.Property<bool>("IsBot")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("longtext CHARACTER SET utf8")
                        .HasMaxLength(4000);

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(256) CHARACTER SET utf8")
                        .HasMaxLength(256);

                    b.Property<int>("TGUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(128) CHARACTER SET utf8")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("TGUserId")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("CNBot.Core.Entities.Users.UserCommand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_command");
                });

            modelBuilder.Entity("CNBot.Core.Entities.Chats.ChatMember", b =>
                {
                    b.HasOne("CNBot.Core.Entities.Chats.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CNBot.Core.Entities.Messages.MessageEntity", b =>
                {
                    b.HasOne("CNBot.Core.Entities.Messages.Message", "Message")
                        .WithMany("MessageEntities")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CNBot.Core.Entities.Users.UserCommand", b =>
                {
                    b.HasOne("CNBot.Core.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
